/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MerkleVerifier,
  MerkleVerifierInterface,
} from "../../src/MerkleVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "courseName",
        type: "string",
      },
      {
        internalType: "string",
        name: "grade",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "hashLeaf",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "leaf",
        type: "bytes32",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103b5806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630a94bed51461003b5780635a9a49c714610061575b600080fd5b61004e6100493660046101e9565b610084565b6040519081526020015b60405180910390f35b61007461006f36600461025d565b6100c0565b6040519015158152602001610058565b6000858585858560405160200161009f959493929190610308565b60405160208183030381529060405280519060200120905095945050505050565b600061010285858080602002602001604051908101604052809392919081815260200183836020028082843760009201919091525087925086915061010b9050565b95945050505050565b6000826101188584610121565b14949350505050565b600081815b8451811015610166576101528286838151811061014557610145610342565b602002602001015161016e565b91508061015e81610358565b915050610126565b509392505050565b600081831061018a576000828152602084905260409020610199565b60008381526020839052604090205b9392505050565b60008083601f8401126101b257600080fd5b50813567ffffffffffffffff8111156101ca57600080fd5b6020830191508360208285010111156101e257600080fd5b9250929050565b60008060008060006060868803121561020157600080fd5b853567ffffffffffffffff8082111561021957600080fd5b61022589838a016101a0565b9097509550602088013591508082111561023e57600080fd5b5061024b888289016101a0565b96999598509660400135949350505050565b6000806000806060858703121561027357600080fd5b843567ffffffffffffffff8082111561028b57600080fd5b818701915087601f83011261029f57600080fd5b8135818111156102ae57600080fd5b8860208260051b85010111156102c357600080fd5b6020928301999098509187013596604001359550909350505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b60608152600061031c6060830187896102df565b828103602084015261032f8186886102df565b9150508260408301529695505050505050565b634e487b7160e01b600052603260045260246000fd5b60006001820161037857634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212207e5bd2fa1a72ad02e7a49599a038d69dea29dd12e6a56f9e2e6e7e418042c1ca64736f6c63430008140033";

type MerkleVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MerkleVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MerkleVerifier__factory extends ContractFactory {
  constructor(...args: MerkleVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MerkleVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MerkleVerifier__factory {
    return super.connect(runner) as MerkleVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MerkleVerifierInterface {
    return new Interface(_abi) as MerkleVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MerkleVerifier {
    return new Contract(address, _abi, runner) as unknown as MerkleVerifier;
  }
}
