/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIssuer"
      | "anchor"
      | "isValidAt"
      | "issuers"
      | "merkleRoots"
      | "removeIssuer"
      | "revocations"
      | "revoke"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialAnchored"
      | "CredentialRevoked"
      | "IssuerAdded"
      | "IssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchor",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revocations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "revoke", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isValidAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
}

export namespace CredentialAnchoredEvent {
  export type InputTuple = [
    credentialHash: BytesLike,
    merkleRoot: BytesLike,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    credentialHash: string,
    merkleRoot: string,
    issuer: string
  ];
  export interface OutputObject {
    credentialHash: string;
    merkleRoot: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [credentialHash: BytesLike, revokedAt: BigNumberish];
  export type OutputTuple = [credentialHash: string, revokedAt: bigint];
  export interface OutputObject {
    credentialHash: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIssuer: TypedContractMethod<[uni: AddressLike], [void], "nonpayable">;

  anchor: TypedContractMethod<
    [credentialHash: BytesLike, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  isValidAt: TypedContractMethod<
    [credentialHash: BytesLike, timestamp: BigNumberish],
    [boolean],
    "view"
  >;

  issuers: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  merkleRoots: TypedContractMethod<
    [credentialHash: BytesLike],
    [string],
    "view"
  >;

  removeIssuer: TypedContractMethod<[uni: AddressLike], [void], "nonpayable">;

  revocations: TypedContractMethod<
    [credentialHash: BytesLike],
    [[boolean, bigint]],
    "view"
  >;

  revoke: TypedContractMethod<
    [credentialHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIssuer"
  ): TypedContractMethod<[uni: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [credentialHash: BytesLike, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidAt"
  ): TypedContractMethod<
    [credentialHash: BytesLike, timestamp: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleRoots"
  ): TypedContractMethod<[credentialHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "removeIssuer"
  ): TypedContractMethod<[uni: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revocations"
  ): TypedContractMethod<
    [credentialHash: BytesLike],
    [[boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[credentialHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "CredentialAnchored"
  ): TypedContractEvent<
    CredentialAnchoredEvent.InputTuple,
    CredentialAnchoredEvent.OutputTuple,
    CredentialAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAdded"
  ): TypedContractEvent<
    IssuerAddedEvent.InputTuple,
    IssuerAddedEvent.OutputTuple,
    IssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRemoved"
  ): TypedContractEvent<
    IssuerRemovedEvent.InputTuple,
    IssuerRemovedEvent.OutputTuple,
    IssuerRemovedEvent.OutputObject
  >;

  filters: {
    "CredentialAnchored(bytes32,bytes32,address)": TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;
    CredentialAnchored: TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerAdded(address)": TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;
    IssuerAdded: TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;

    "IssuerRemoved(address)": TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
    IssuerRemoved: TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
  };
}
