#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════
#  CredChain — End-to-End Demo Script
#  Usage (from project root):  bash scripts/demo.sh
#         (from frontend/):    npm run demo
#
#  1. Start Hardhat local node (port 8545)
#  2. Deploy MerkleVerifier + CredentialRegistry
#  3. Write addresses to frontend/.env
#  4. Start React frontend (http://localhost:5173)
# ════════════════════════════════════════════════════════════════

set -e
C='\033[0;36m'; G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1m'; N='\033[0m'

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND="$ROOT/frontend"
CONTRACTS="$ROOT/contracts"

log()  { echo -e "${C}[demo]${N} $*"; }
ok()   { echo -e "${G}[✓]${N}   $*"; }
warn() { echo -e "${Y}[!]${N}   $*"; }
err()  { echo -e "${R}[✗]${N}   $*"; exit 1; }

echo ""
echo -e "${B}${C}╔══════════════════════════════════════╗${N}"
echo -e "${B}${C}║   CredChain Demo                     ║${N}"
echo -e "${B}${C}╚══════════════════════════════════════╝${N}"
echo ""

# ── Prerequisites ──────────────────────────────────────────────
command -v node >/dev/null 2>&1 || err "Node.js not found"
command -v npm  >/dev/null 2>&1 || err "npm not found"
ok "Node $(node -v)"

# ── Install deps ───────────────────────────────────────────────
log "Installing dependencies..."
cd "$ROOT" && npm install --silent
ok "Root workspace deps ready"

# ── Start Hardhat node ─────────────────────────────────────────
log "Starting Hardhat node on :8545..."
pkill -f "hardhat node" 2>/dev/null || true; sleep 1

cd "$CONTRACTS"
npx hardhat node --hostname 127.0.0.1 > /tmp/hardhat.log 2>&1 &
HH_PID=$!
echo "$HH_PID" > /tmp/hardhat.pid

# Wait for node
for i in $(seq 1 20); do
  curl -s -X POST -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
    http://127.0.0.1:8545 >/dev/null 2>&1 && break
  [ "$i" -eq 20 ] && err "Hardhat node failed — check /tmp/hardhat.log"
  sleep 0.5
done
ok "Hardhat node running (PID $HH_PID)"

# ── Deploy contracts ───────────────────────────────────────────
log "Deploying CredentialRegistry + MerkleVerifier..."
cd "$CONTRACTS"
DEPLOY=$(npx hardhat run ../scripts/deploy/deploy.ts --network localhost 2>&1)
echo "$DEPLOY"

# Extract addresses — deploy.ts prints:
#   ✅ MerkleVerifier deployed to: 0x...
#   ✅ CredentialRegistry deployed to: 0x...
VERIFIER_ADDR=$(echo "$DEPLOY" | grep -i "MerkleVerifier deployed"     | grep -oP '0x[0-9a-fA-F]{40}' | head -1)
REGISTRY_ADDR=$(echo "$DEPLOY" | grep -i "CredentialRegistry deployed" | grep -oP '0x[0-9a-fA-F]{40}' | head -1)

if [ -z "$VERIFIER_ADDR" ] || [ -z "$REGISTRY_ADDR" ]; then
  warn "Could not parse addresses from deploy output."
  warn "Please manually set them in frontend/.env"
  VERIFIER_ADDR="0x0000000000000000000000000000000000000000"
  REGISTRY_ADDR="0x0000000000000000000000000000000000000000"
else
  ok "MerkleVerifier:      $VERIFIER_ADDR"
  ok "CredentialRegistry:  $REGISTRY_ADDR"
fi

# ── Write frontend/.env ────────────────────────────────────────
log "Writing frontend/.env..."
cat > "$FRONTEND/.env" <<EOF
# Auto-generated by demo.sh on $(date)
VITE_REGISTRY_ADDRESS=$REGISTRY_ADDR
VITE_VERIFIER_ADDRESS=$VERIFIER_ADDR
VITE_NETWORK=localhost
EOF
ok ".env written"

# ── Start frontend ─────────────────────────────────────────────
log "Starting frontend..."
cd "$FRONTEND" && npm install --silent

echo ""
echo -e "${B}${G}════════════════════════════════════════════${N}"
echo -e "${B}${G}  CredChain is ready!                       ${N}"
echo -e "${B}${G}  → http://localhost:5173                   ${N}"
echo -e "${B}${G}  /issue   — University wallet              ${N}"
echo -e "${B}${G}  /prove   — Student (upload credential)    ${N}"
echo -e "${B}${G}  /verify  — Employer (upload proof)        ${N}"
echo -e "${B}${G}════════════════════════════════════════════${N}"
echo ""
echo -e "${Y}MetaMask setup:${N}"
echo "  Network: Localhost 8545 · Chain ID: 31337"
echo "  Issuer key (Hardhat #1): 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
echo ""

# Open browser
(sleep 2 && (command -v xdg-open >/dev/null 2>&1 && xdg-open http://localhost:5173 || \
             command -v open     >/dev/null 2>&1 && open     http://localhost:5173 || true)) &

trap 'log "Shutting down..."; kill $HH_PID 2>/dev/null; exit 0' SIGINT SIGTERM
npm run dev
