//FILE: MerkleVerifier.sol 
/*
Purpose : Pure Merkle proof verification logic. Stateless library contract.

Functions:
  verify(
    bytes32[] calldata proof,
    bytes32   root,
    bytes32   leaf
  ) public pure → bool
    └─ uses OpenZeppelin MerkleProof.verify() with sorted pair hashing
    └─ sorted pair: if (a < b) hash(a,b) else hash(b,a)

  hashLeaf(
    string calldata courseName,
    string calldata grade,
    bytes32        salt
  ) public pure → bytes32
    └─ returns keccak256(abi.encode(courseName, grade, salt))
    └─ salt prevents brute-force enumeration (from P5)
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/**
 * ============================================================================
 * @title MerkleVerifier
 * @dev Pure stateless library contract responsible for Merkle proof verification.
 * It allows anyone to verify that a specific course grade (leaf) is part of a
 * student's anchored credential (root) without revealing other grades.
 * ============================================================================
 */
contract MerkleVerifier {
    /**
     * @dev Verifies a Merkle proof proving that a leaf is part of a tree with a given root.
     * Uses OpenZeppelin's MerkleProof library which implements sorted pair hashing.
     * @param proof The Merkle proof array of hashes generated by the student.
     * @param root The Merkle root anchored on the blockchain by the university.
     * @param leaf The hash of the specific course data being verified.
     * @return bool True if the cryptographic proof is valid, false otherwise.
     */
    function verify(bytes32[] calldata proof, bytes32 root, bytes32 leaf) public pure returns (bool) {
        // MerkleProof.verify automatically handles sorted pair hashing:
        // if (a < b) hash(a,b) else hash(b,a)
        return MerkleProof.verify(proof, root, leaf);
    }

    /**
     * @dev Generates the hash of a leaf node (a single course/grade entry).
     * The salt ensures privacy so attackers cannot brute-force guess the grades.
     * @param courseName The name of the course (e.g., "Web Development").
     * @param grade The grade achieved (e.g., "A").
     * @param salt A random 32-byte string assigned to this specific course.
     * @return bytes32 The keccak256 hash of the abi-encoded parameters.
     */
    function hashLeaf(string calldata courseName, string calldata grade, bytes32 salt) public pure returns (bytes32) {
        return keccak256(abi.encode(courseName, grade, salt));
    }
}